### ISSUE TITLE
Add support for default/global versions

### ISSUE THREAD

**Issue by anthonator** [HashNuke/asdf#11]
Provide the ability to set default system wide versions.

**Comment by HashNuke** [comment]
@anthonator You can do that by having a `.tool-versions` file in your home directory (`$HOME/.tool-versions`)

If there's no `.tool-versions` file in the current directory, asdf will traverse parent directories. If all fail, then the file at `$HOME/.tool-versions` will be used.

Thanks for asking. I'll check the readme and make this clear.

Closing this issue. Let me know if there's anything else :)
