### ISSUE TITLE
No version set for ...

### ISSUE THREAD

**Issue by maarek** [HashNuke/asdf#14]
Installed asdf on OSX Yosemite
Installed necessary brews
Set up plugin for erlang (asdf plugin-add erlang https://github.com/HashNuke/asdf-erlang.git)
Installed Erlang (asdf install erlang 17.5)
Get No version set for erlang

The same happens for elixir as well.

Might be related to a pathing issue that I had while installing asdf. 

In ~/.asdf/asdf.sh current_script_path=${BASH_SOURCE[0]} returns an empty string. I changed it it .asdf so that asdf exports properly. I am currently using zsh.

**Comment by HashNuke** [comment]
@maarek Do you have "bash" aliased to zsh?

**Comment by HashNuke** [comment]
@maarek Checked with zsh and pushed a fix.

* Please run `git pull origin master` within your `$HOME/.asdf` dir.
* Changed the installation instructions too. In your .zshrc, you'll have to change `source $HOME/asdf/.asdf.sh` to `. $HOME/asdf/.asdf.sh`

In short, use the dot operator instead of `source`. Let me know how it goes.

**Comment by maarek** [comment]
@HashNuke I modified to you instructions and it's still not finding a version set for the install. I tried wiping the .asdf directory and starting over as well without any luck.

**Comment by HashNuke** [comment]
@maarek can you get me the following info?

* path of the .tool-versions file
* contents of the .tool-versions file
* command you tried to run
* any errors you get

**Comment by maarek** [comment]
@HashNuke That was it. Didn't realize it was something that needed to be done (at least globally).

**Comment by henrik** [comment]
I got the error

> asdf: No version set for command bundle

trying to run `bundle` after upgrading Ruby via asdf. The error message was confusing, suggesting versions earlier than the one I had installed (2.5.5):

```
$ bundle
asdf: No version set for command bundle
you might want to add one of the following in your .tool-versions file:

ruby 1.9.3-p551
ruby 2.2.5
ruby 2.4.1
ruby 2.4.4
ruby 2.5.1
```

What fixed it for me was simply to `gem install bundle`.

**Comment by gaelant** [comment]
> I got the error
> 
> > asdf: No version set for command bundle
> 
> trying to run `bundle` after upgrading Ruby via asdf. The error message was confusing, suggesting versions earlier than the one I had installed (2.5.5):
> 
> ```
> $ bundle
> asdf: No version set for command bundle
> you might want to add one of the following in your .tool-versions file:
> 
> ruby 1.9.3-p551
> ruby 2.2.5
> ruby 2.4.1
> ruby 2.4.4
> ruby 2.5.1
> ```
> 
> What fixed it for me was simply to `gem install bundle`.

Also for people who recently upgraded Ruby, don't forget to run `bundle install` after @henrik 's suggestion.
