### ISSUE TITLE
Erlang 18.0 - No version set for erlang

### ISSUE THREAD

**Issue by wicliff** [HashNuke/asdf#18]
Installed Erlang 18.0 and setup the .tool-versions to erlang 18.0.

When running the elixir or erlang command line, it gives the following error
`
No version set for erlang
`

Using OSX/zsh

**Comment by HashNuke** [comment]
@wicliff What's the path to your tool-versions file?
You can have one in your $HOME for global versions and another in your project directory

**Comment by wicliff** [comment]
The current one is the $HOME. 
Not set in any in the project directory.

[Solved]
Also cat .tool-versions showed this, which was created using vim
`
erlang 18.0%
`
Made changes using nano, so now it works properly.
