### ISSUE TITLE
If "asdf install" fails, it should realise this

### ISSUE THREAD

**Issue by palfrey** [HashNuke/asdf#19]
Did "asdf install ruby 2.2.2", and the compile failed. However, attempts to fix this and do "asdf install ruby 2.2.2" again got me "ruby 2.2.2 is already installed" when it very much wasn't...

**Comment by HashNuke** [comment]
@palfrey Thank you for reporting this. Yes this is a bug.
This is what happens: when an install command is called, it creates directories for installation paths and hands it over to respective plugins. It needs to delete these directories if the install command fails.

I'll fix it up tomorrow.

**Comment by HashNuke** [comment]
@palfrey temporarily, you can delete the installation directory for ruby 2.2.2 manually. The dir is `~/.asdf/installs/ruby/2.2.2`

**Comment by HashNuke** [comment]
@palfrey Fixed in master ~! Running `git pull origin master` in your `$HOME/.asdf` dir will fix the install command.

**Comment by MSch** [comment]
This didn't work for me when trying to `asdf install elixir master` on the latest master, I still had an empty `~/.asdf/installs/elixir/master` directory.

**Comment by HashNuke** [comment]
@MSch for any git ref the version needs to be specified as `ref:foobar`. The command to install master would be `asdf install elixir ref:master`

**Comment by MSch** [comment]
@HashNuke I know, I figured this out later :) But when I didn't realize this yet I used `asdf install elixir master` and that left an empty `~/.asdf/installs/elixir/master` directory even though the installation (obviously) failed.

**Comment by HashNuke** [comment]
@MSch Thank you for reporting this ~! Fixed it.
You'll have to update the elixir plugin with `asdf plugin-update elixir`
