### ISSUE TITLE
.tool-versions needs a blank newline?

### ISSUE THREAD

**Issue by mylanconnolly** [HashNuke/asdf#28]
Just wanted to verify this. I didn't see mention of it in the documentation, but I noticed that if there is no trailing blank line in `.tool-versions` the last line in the file does not get read.

As an example, I had the following contents:

```
erlang 18.2.1
elixir 1.2.2
ruby 2.3.0
nodejs 5.5.0
```

I noticed that it wasn't setting Node; I was getting the error that there was no version configured. To test, I shuffled it around so that Ruby was last and then Node worked but Ruby did not.

After I noticed that I added a blank line after the last item and all items seem to be working properly.

I'm not sure if it's worth changing or just putting some mention up in the README. It's definitely easy to work around (and some editors add the trailing line automatically anyway).

Otherwise, thanks! I really like this version manager.

**Comment by Stratus3D** [comment]
I am on Ubuntu 14.04 and OSX 10.10.5 and I have not experienced this issue. I tried with and without a trailing line and wasn't able to replicate this issue. 

Do you know what line endings you editor uses?

**Comment by HashNuke** [comment]
@mylanconnolly can you try updating to the latest version of asdf? I remember fixing this issue long ago.

**Comment by reignmaker** [comment]
I had the same issue - no new line in `.tool-version`.
Ubuntu 14.04.3 LTS

**Comment by HashNuke** [comment]
@reignmaker @mylanconnolly This issue was already fixed weeks (or months) ago AFAIK. Try updating asdf to the latest version using the commands below:

```
cd ~/.asdf
git pull origin master
```

I'll add an update command later today. Closing the issue for now. If you still have the issue after updating, then please reopen it.

@Stratus3D Trevor thanks for pitching in ~!

**Comment by Stratus3D** [comment]
@HashNuke if you add an update command you might also want to start tagging the repo and add a version command that pulls in that tag info. Something like `asdf --version` or `asdf version` might help with debugging in the future.

**Comment by mylanconnolly** [comment]
Hey all.

Sorry for the delay on the response (been pretty busy).

I was using vim, which should be using the Linux line encoding.

I was already on the newest version of asdf (and still am, it seems). When I try to recreate the issue, I cannot, so that's kinda bizarre (but good). Looks like I may have jumped the gun a bit.

**Comment by HashNuke** [comment]
@mylanconnolly No worries. Happy to help. Please do report back if you encounter this issue again.
